name: cluster_manager_geomodo
description: Simple Flutter clustering library for Google Maps based on Geohash.
publish_to: 'none'
version: 0.5.3+5
homepage: https://github.com/bpillon/google_maps_cluster_manager

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
